import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { SignIn, SignOutButton, useUser } from "@clerk/nextjs";

import { api } from "~/utils/api";

const Home: NextPage = () => {
  const user = useUser();
  const { data } = api.golfer.getAll.useQuery();
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center  bg-gradient-to-b from-[#2e026d] to-[#15162c]">
        <div className="bg-slate-200 w-full max-w-2xl p-4">
		  {!user.isSignedIn && <SignIn />}
		  <h1>{!!user.isSignedIn && <SignOutButton />}</h1>
        </div>
        <div className="flex flex-col w-full max-w-2xl p-4 bg-slate-600">
		{data?.map((golfer) => (<div>{golfer.name} {golfer.handicap}</div>))}
        </div>
      </main>
    </>
  );
};

export default Home;
